# Generated by Django 5.0 on 2023-12-19 23:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax_credit', '0001_install_trigram_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusBlockGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fips', models.CharField(max_length=255)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('population', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'tax_credit_census_block_group',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fips', models.CharField(blank=True, default='', max_length=255)),
                ('as_of', models.DateField()),
                ('published_on', models.DateField(null=True)),
                ('source', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'tax_credit_geography',
            },
        ),
        migrations.CreateModel(
            name='GeographyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tax_credit_geography_type',
            },
        ),
        migrations.CreateModel(
            name='GeographyTypeProgram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount_description', models.TextField()),
            ],
            options={
                'db_table': 'tax_credit_geography_type_program',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('agency', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('base_benefit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetBonusAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_geography_type', models.CharField(max_length=255)),
                ('bonus_geography_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tax_credit_target_bonus_assoc',
            },
        ),
        migrations.AddConstraint(
            model_name='censusblockgroup',
            constraint=models.UniqueConstraint(fields=('fips', 'year'), name='unique_census_block_group'),
        ),
        migrations.AddField(
            model_name='geography',
            name='geography_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_credit.geographytype'),
        ),
        migrations.AddField(
            model_name='geographytypeprogram',
            name='geography_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_credit.geographytype'),
        ),
        migrations.AddField(
            model_name='geographytypeprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_credit.program'),
        ),
        migrations.AddField(
            model_name='targetbonusassoc',
            name='bonus_geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_geo_set', to='tax_credit.geography'),
        ),
        migrations.AddField(
            model_name='targetbonusassoc',
            name='target_geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_geo_set', to='tax_credit.geography'),
        ),
        migrations.AddConstraint(
            model_name='geography',
            constraint=models.UniqueConstraint(fields=('name', 'geography_type', 'fips'), name='unique_geography'),
        ),
        migrations.AlterUniqueTogether(
            name='geographytypeprogram',
            unique_together={('geography_type', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='targetbonusassoc',
            unique_together={('target_geography', 'bonus_geography')},
        ),
    ]
