# Generated by Django 5.0.4 on 2024-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_credit', '0003_install_trigram_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
